name: smart_farmer
description: "المزارع الذكي: تشخيص أمراض النباتات أوفلاين + إدارة محاصيل + طقس + سجل محلي"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # واجهة
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.9.0

  # نظام وتشغيل
  url_launcher: ^6.3.0
  http: ^1.2.2
  intl: ^0.19.0

  # صور/كاميرا ومعالجة
  image_picker: ^1.2.0
  image: ^4.1.7

  # قاعدة بيانات وملفات
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0

  # موقع + طقس
  geolocator: ^13.0.2

  # ذكاء اصطناعي (TFLite) — بدون helper
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    # بيانات المحاصيل (أوفلاين)
    - assets/crops/metadata.json

    # ملفات نموذج الذكاء الاصطناعي
    # (تأكد من وجودها فعليًا أو علّق السطرين مؤقتًا لتفادي Missing asset)
    - assets/model/plant_disease.tflite
    - assets/model/labels.txt
